/**
 * Zod Validation Schemas
 * Centralized validation for API inputs
 */

import { z } from 'zod';

// Contract status enum - matches database and UI
export const CONTRACT_STATUSES = [
  'Discussions Not Started',
  'Initial Agreement Development',
  'Review & Redlines',
  'Approval & Signature',
  'Agreement Submission',
  'PO Received',
] as const;

// Task status and priority enums
export const TASK_STATUSES = ['pending', 'in_progress', 'completed', 'cancelled'] as const;
export const TASK_PRIORITIES = ['low', 'medium', 'high', 'urgent'] as const;

// Date string validation (YYYY-MM-DD format)
const dateString = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must be in YYYY-MM-DD format');

// Salesforce ID validation (15 or 18 character alphanumeric)
const salesforceId = z.string().regex(/^[a-zA-Z0-9]{15,18}$/, 'Invalid Salesforce ID');

/**
 * Contract Update Schema
 * Used for PATCH /api/contracts
 */
export const contractUpdateSchema = z.object({
  status: z.enum(CONTRACT_STATUSES).optional(),
  value: z.number().min(0, 'Value must be non-negative').optional(),
  closeDate: dateString.optional().nullable(),
  awardDate: dateString.optional().nullable(),
  contractDate: dateString.optional().nullable(),
  installDate: dateString.optional().nullable(),
  probability: z.number().min(0).max(100).optional(),
  budgeted: z.boolean().optional(),
  manualCloseProbability: z.number().min(0).max(100).optional().nullable(),
  salesRep: z.string().max(255).optional(),
  redlines: z.string().optional(),
}).strict();

/**
 * Task Create Schema
 * Used for POST /api/tasks
 */
export const taskCreateSchema = z.object({
  title: z.string().min(1, 'Title is required').max(500, 'Title too long'),
  description: z.string().max(5000).optional(),
  status: z.enum(TASK_STATUSES).default('pending'),
  priority: z.enum(TASK_PRIORITIES).default('medium'),
  contractId: z.string().uuid().optional(),
  contractSalesforceId: salesforceId.optional(),
  contractName: z.string().max(255).optional(),
  contractStage: z.string().max(100).optional(),
  isAutoGenerated: z.boolean().default(false),
  taskTemplateId: z.string().max(50).optional(),
  dueDate: dateString.optional().nullable(),
  assigneeEmail: z.string().email().optional().nullable(),
});

/**
 * Task Update Schema
 * Used for PATCH /api/tasks
 */
export const taskUpdateSchema = z.object({
  id: z.string().uuid('Invalid task ID'),
  title: z.string().min(1).max(500).optional(),
  description: z.string().max(5000).optional(),
  status: z.enum(TASK_STATUSES).optional(),
  priority: z.enum(TASK_PRIORITIES).optional(),
  dueDate: dateString.optional().nullable(),
  assigneeEmail: z.string().email().optional().nullable(),
  completedAt: z.string().datetime().optional().nullable(),
}).strict();

/**
 * Document Create Schema
 * Used for POST /api/contracts/documents
 */
export const documentCreateSchema = z.object({
  contractId: z.string().uuid().optional(),
  salesforceId: salesforceId.optional(),
  accountName: z.string().min(1, 'Account name is required').max(255),
  opportunityName: z.string().max(255).optional(),
  opportunityYear: z.number().int().min(1).max(10).optional(),
  documentType: z.enum([
    'Original Contract',
    'MARS Redlines',
    'Client Response',
    'Final Agreement',
    'Executed Contract',
    'Purchase Order',
    'Amendment',
    'Other',
  ]),
  status: z.enum([
    'draft',
    'under_review',
    'awaiting_signature',
    'executed',
    'expired',
    'superseded',
  ]).default('draft'),
  fileName: z.string().min(1, 'File name is required').max(500),
  fileUrl: z.string().url('Invalid file URL'),
  fileSize: z.number().int().positive().optional(),
  fileMimeType: z.string().max(100).optional(),
  expirationDate: dateString.optional().nullable(),
  effectiveDate: dateString.optional().nullable(),
  uploadedBy: z.string().max(255).optional(),
  notes: z.string().max(2000).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
});

/**
 * Helper to safely parse and return typed result
 */
export function validateOrThrow<T>(schema: z.ZodSchema<T>, data: unknown): T {
  return schema.parse(data);
}

/**
 * Helper to validate and return result with error messages
 */
export function validateSafe<T>(schema: z.ZodSchema<T>, data: unknown): {
  success: boolean;
  data?: T;
  errors?: string[];
} {
  const result = schema.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    errors: result.error.issues.map(e => `${e.path.join('.')}: ${e.message}`),
  };
}
